// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfR-0N8962BdVQplJORolq75gyY6Jae4s',
    appId: '1:506690888246:web:d15e4b31f1319bf0a1ee97',
    messagingSenderId: '506690888246',
    projectId: 'pawtopia-7db32',
    authDomain: 'pawtopia-7db32.firebaseapp.com',
    storageBucket: 'pawtopia-7db32.firebasestorage.app',
    measurementId: 'G-3MNZQ2ZEPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4Mchjm4x58xgAN2RzhdZiqhsC2ZoCYw',
    appId: '1:506690888246:android:a44d95bcdaac73aca1ee97',
    messagingSenderId: '506690888246',
    projectId: 'pawtopia-7db32',
    storageBucket: 'pawtopia-7db32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOZmvqQeYewt17ZkhDbRfPZ7GrrTnmaHw',
    appId: '1:506690888246:ios:b5f26bb943726ce3a1ee97',
    messagingSenderId: '506690888246',
    projectId: 'pawtopia-7db32',
    storageBucket: 'pawtopia-7db32.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOZmvqQeYewt17ZkhDbRfPZ7GrrTnmaHw',
    appId: '1:506690888246:ios:b5f26bb943726ce3a1ee97',
    messagingSenderId: '506690888246',
    projectId: 'pawtopia-7db32',
    storageBucket: 'pawtopia-7db32.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfR-0N8962BdVQplJORolq75gyY6Jae4s',
    appId: '1:506690888246:web:470a6360a7a48743a1ee97',
    messagingSenderId: '506690888246',
    projectId: 'pawtopia-7db32',
    authDomain: 'pawtopia-7db32.firebaseapp.com',
    storageBucket: 'pawtopia-7db32.firebasestorage.app',
    measurementId: 'G-5C6169XK60',
  );
}
